### ISSUE TITLE
Waylaid Supplies: Deadly Scopes  wrong Gold reward

### ISSUE THREAD

**Issue by silverselo** [saimpot/WaylaidSuppliesGoldCost#2]
Waylaid Supplies: Deadly Scopes 

Addon says Gold Reward: 5g50s instead of 12g

but it actually gives 12g see https://www.wowhead.com/classic/item=215403/waylaid-supplies-deadly-scopes#comments > follow up https://www.wowhead.com/classic/item=217339/supply-shipment#objective-of

**Comment by saimpot** [comment]
Hello. Thanks for the report @silverselo . It will be fixed with today's update.

**Comment by saimpot** [comment]
Fixed in [ba63e63](https://github.com/saimpot/WaylaidSuppliesGoldCost/commit/ba63e63534982fd3acfdf1682463cfc904469c2a).
